# .NET Core
trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  runtimeIdentifier: win-x64

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreInstaller@1
  inputs:
    includePreviewVersions: true
    packageType: sdk
    version: 3.0.100-preview6-012264

- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: publish
    projects: src/QuickWindows/QuickWindows.csproj
    arguments: --configuration $(buildConfiguration) --runtime $(runtimeIdentifier) --self-contained true --output $(build.ArtifactStagingDirectory)
    zipAfterPublish: true

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
